"""initial schema

Revision ID: 71a95c1d2c41
Revises: 
Create Date: 2026-03-24 02:46:42.248557
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a95c1d2c41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('province', sa.String(length=2), nullable=False),
    sa.Column('api_token_enc', sa.String(), nullable=False),
    sa.Column('pos_system', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_company_id'), 'locations', ['company_id'], unique=False)
    op.create_table('compliance_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('opening_qty', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('qty_received', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('qty_sold', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('qty_adjusted', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('closing_qty', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('greenline_closing_qty', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('discrepancy_delta', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'product_id', 'report_date', name='uq_snapshot_day')
    )
    op.create_index(op.f('ix_compliance_snapshots_product_id'), 'compliance_snapshots', ['product_id'], unique=False)
    op.create_index(op.f('ix_compliance_snapshots_report_date'), 'compliance_snapshots', ['report_date'], unique=False)
    op.create_index('ix_snapshot_lookup', 'compliance_snapshots', ['location_id', 'report_date'], unique=False)
    op.create_table('raw_pos_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('external_event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('gram_equivalency', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'external_event_id', name='uq_event_idempotent')
    )
    op.create_index(op.f('ix_raw_pos_events_external_event_id'), 'raw_pos_events', ['external_event_id'], unique=False)
    op.create_index(op.f('ix_raw_pos_events_location_id'), 'raw_pos_events', ['location_id'], unique=False)
    op.create_table('compliance_discrepancies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('internal_qty', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('greenline_qty', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('delta', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['compliance_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_discrepancies_location_id'), 'compliance_discrepancies', ['location_id'], unique=False)
    op.create_index(op.f('ix_compliance_discrepancies_report_date'), 'compliance_discrepancies', ['report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_discrepancies_report_date'), table_name='compliance_discrepancies')
    op.drop_index(op.f('ix_compliance_discrepancies_location_id'), table_name='compliance_discrepancies')
    op.drop_table('compliance_discrepancies')
    op.drop_index(op.f('ix_raw_pos_events_location_id'), table_name='raw_pos_events')
    op.drop_index(op.f('ix_raw_pos_events_external_event_id'), table_name='raw_pos_events')
    op.drop_table('raw_pos_events')
    op.drop_index('ix_snapshot_lookup', table_name='compliance_snapshots')
    op.drop_index(op.f('ix_compliance_snapshots_report_date'), table_name='compliance_snapshots')
    op.drop_index(op.f('ix_compliance_snapshots_product_id'), table_name='compliance_snapshots')
    op.drop_table('compliance_snapshots')
    op.drop_index(op.f('ix_locations_company_id'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
