"""
VeriLeaf — Dual-Track Audit Ledger (SQLAlchemy 2.0 Mapped)

Track 1: RawEvent         — Immutable webhook payloads from Greenline POS
Track 2: DailySnapshot    — Reconciled "Golden Record" for government reports
Track 3: Discrepancy      — Flagged drift requiring manager acknowledgement
"""
import uuid
from decimal import Decimal
from datetime import datetime, date

from sqlalchemy import (
    String, DECIMAL, DateTime, ForeignKey, JSON, Boolean, Date, Integer, Text,
    UniqueConstraint, Index,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


# ── Location (multi-tenant anchor) ──────────────────────────────────────────

class Location(Base):
    __tablename__ = "locations"

    id: Mapped[str] = mapped_column(String, primary_key=True)       # POS location ID
    company_id: Mapped[str] = mapped_column(String, index=True)
    store_name: Mapped[str] = mapped_column(String, default="")
    province: Mapped[str] = mapped_column(String(2))                 # ON, AB, BC, QC …
    api_token_enc: Mapped[str] = mapped_column(String)               # Fernet-encrypted
    pos_system: Mapped[str] = mapped_column(String(20), default="greenline")  # greenline | blaze
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    snapshots: Mapped[list["DailyComplianceSnapshot"]] = relationship(back_populates="location")
    events: Mapped[list["RawPosEvent"]] = relationship(back_populates="location")


# ── Track 1: Immutable Event Log ────────────────────────────────────────────

class RawPosEvent(Base):
    """
    Every webhook payload lands here ONCE and is never mutated.
    Idempotency key = (location_id, external_event_id).
    """
    __tablename__ = "raw_pos_events"
    __table_args__ = (
        UniqueConstraint("location_id", "external_event_id", name="uq_event_idempotent"),
    )

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    location_id: Mapped[str] = mapped_column(ForeignKey("locations.id"), index=True)
    external_event_id: Mapped[str] = mapped_column(String, index=True)  # Greenline sale/adj ID
    event_type: Mapped[str] = mapped_column(String(30))                 # sale.created, adjustment, receive
    payload: Mapped[dict] = mapped_column(JSON)                         # Full webhook body
    gram_equivalency: Mapped[Decimal] = mapped_column(DECIMAL(12, 3), default=0)
    received_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    location: Mapped["Location"] = relationship(back_populates="events")


# ── Track 2: Compliance Snapshot ("Golden Record") ──────────────────────────

class DailyComplianceSnapshot(Base):
    """
    One row per (location, product, date).
    Generated by the Midnight Reconciliation Engine.
    This is the ONLY source-of-truth for government reports.
    """
    __tablename__ = "compliance_snapshots"
    __table_args__ = (
        UniqueConstraint("location_id", "product_id", "report_date", name="uq_snapshot_day"),
        Index("ix_snapshot_lookup", "location_id", "report_date"),
    )

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    location_id: Mapped[str] = mapped_column(ForeignKey("locations.id"))
    report_date: Mapped[date] = mapped_column(Date, index=True)
    product_id: Mapped[str] = mapped_column(String, index=True)
    sku: Mapped[str] = mapped_column(String, default="")
    product_name: Mapped[str] = mapped_column(String, default="")
    category: Mapped[str] = mapped_column(String(30), default="")     # dried, extract, edible …

    # Mass-balance columns (grams or gram-equivalent)
    opening_qty: Mapped[Decimal] = mapped_column(DECIMAL(12, 3), default=0)
    qty_received: Mapped[Decimal] = mapped_column(DECIMAL(12, 3), default=0)
    qty_sold: Mapped[Decimal] = mapped_column(DECIMAL(12, 3), default=0)
    qty_adjusted: Mapped[Decimal] = mapped_column(DECIMAL(12, 3), default=0)
    closing_qty: Mapped[Decimal] = mapped_column(DECIMAL(12, 3), default=0)

    # Reconciliation state
    greenline_closing_qty: Mapped[Decimal] = mapped_column(DECIMAL(12, 3), default=0)
    is_reconciled: Mapped[bool] = mapped_column(Boolean, default=False)
    discrepancy_delta: Mapped[Decimal] = mapped_column(DECIMAL(12, 3), default=0)

    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    location: Mapped["Location"] = relationship(back_populates="snapshots")


# ── Track 3: Discrepancy Register ───────────────────────────────────────────

class ComplianceDiscrepancy(Base):
    """
    Created whenever |internal_closing - greenline_closing| > tolerance.
    Reports CANNOT be generated for a date until all discrepancies are
    acknowledged (manager must set acknowledged=True).
    """
    __tablename__ = "compliance_discrepancies"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    snapshot_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("compliance_snapshots.id"))
    location_id: Mapped[str] = mapped_column(ForeignKey("locations.id"), index=True)
    report_date: Mapped[date] = mapped_column(Date, index=True)
    product_id: Mapped[str] = mapped_column(String)

    internal_qty: Mapped[Decimal] = mapped_column(DECIMAL(12, 3))
    greenline_qty: Mapped[Decimal] = mapped_column(DECIMAL(12, 3))
    delta: Mapped[Decimal] = mapped_column(DECIMAL(12, 3))

    acknowledged: Mapped[bool] = mapped_column(Boolean, default=False)
    acknowledged_by: Mapped[str | None] = mapped_column(String, nullable=True)
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
